// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/17/2025, 10:55:02 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/home/gert/gitProjects/sporty-ski-reisvinder/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/gert/gitProjects/sporty-ski-reisvinder/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/gert/gitProjects/sporty-ski-reisvinder/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/gert/gitProjects/sporty-ski-reisvinder/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/gert/gitProjects/sporty-ski-reisvinder/plugins/**/*.{js,ts,mjs}","/home/gert/gitProjects/sporty-ski-reisvinder/composables/**/*.{js,ts,mjs}","/home/gert/gitProjects/sporty-ski-reisvinder/utils/**/*.{js,ts,mjs}","/home/gert/gitProjects/sporty-ski-reisvinder/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/gert/gitProjects/sporty-ski-reisvinder/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/gert/gitProjects/sporty-ski-reisvinder/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/gert/gitProjects/sporty-ski-reisvinder/app.config.{js,ts,mjs}","/home/gert/gitProjects/sporty-ski-reisvinder/app/spa-loading-template.html"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;