// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 13/10/2025, 21:50:18
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Users/gerts/Downloads/sporty-ski-reisvinder/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/gerts/Downloads/sporty-ski-reisvinder/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/gerts/Downloads/sporty-ski-reisvinder/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/gerts/Downloads/sporty-ski-reisvinder/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/gerts/Downloads/sporty-ski-reisvinder/plugins/**/*.{js,ts,mjs}","C:/Users/gerts/Downloads/sporty-ski-reisvinder/composables/**/*.{js,ts,mjs}","C:/Users/gerts/Downloads/sporty-ski-reisvinder/utils/**/*.{js,ts,mjs}","C:/Users/gerts/Downloads/sporty-ski-reisvinder/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/gerts/Downloads/sporty-ski-reisvinder/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/gerts/Downloads/sporty-ski-reisvinder/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/gerts/Downloads/sporty-ski-reisvinder/app.config.{js,ts,mjs}","C:/Users/gerts/Downloads/sporty-ski-reisvinder/app/spa-loading-template.html"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;